# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classes.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 360)
        self.title_name = QtWidgets.QLabel(Dialog)
        self.title_name.setGeometry(QtCore.QRect(10, 0, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_name.setFont(font)
        self.title_name.setStyleSheet("font: 14pt \"Source Sans Pro\";")
        self.title_name.setAlignment(QtCore.Qt.AlignCenter)
        self.title_name.setObjectName("title_name")
        self.listWidget_students = QtWidgets.QListWidget(Dialog)
        self.listWidget_students.setGeometry(QtCore.QRect(20, 90, 411, 251))
        self.listWidget_students.setObjectName("listWidget_students")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 30, 461, 16))
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.comboBox_class_number = QtWidgets.QComboBox(Dialog)
        self.comboBox_class_number.setGeometry(QtCore.QRect(20, 50, 41, 25))
        self.comboBox_class_number.setObjectName("comboBox_class_number")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_number.addItem("")
        self.comboBox_class_letter = QtWidgets.QComboBox(Dialog)
        self.comboBox_class_letter.setGeometry(QtCore.QRect(70, 50, 31, 25))
        self.comboBox_class_letter.setObjectName("comboBox_class_letter")
        self.comboBox_class_letter.addItem("")
        self.comboBox_class_letter.addItem("")
        self.comboBox_class_letter.addItem("")
        self.comboBox_class_letter.addItem("")
        self.button_add_student = QtWidgets.QPushButton(Dialog)
        self.button_add_student.setGeometry(QtCore.QRect(280, 50, 151, 25))
        self.button_add_student.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.button_add_student.setObjectName("button_add_student")
        self.button_show_student = QtWidgets.QPushButton(Dialog)
        self.button_show_student.setGeometry(QtCore.QRect(110, 50, 151, 25))
        self.button_show_student.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.button_show_student.setObjectName("button_show_student")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_name.setText(_translate("Dialog", "Классы"))
        self.comboBox_class_number.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_class_number.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_class_number.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_class_number.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_class_number.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_class_number.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_class_number.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_class_number.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_class_number.setItemText(8, _translate("Dialog", "9"))
        self.comboBox_class_number.setItemText(9, _translate("Dialog", "10"))
        self.comboBox_class_number.setItemText(10, _translate("Dialog", "11"))
        self.comboBox_class_letter.setItemText(0, _translate("Dialog", "А"))
        self.comboBox_class_letter.setItemText(1, _translate("Dialog", "Б"))
        self.comboBox_class_letter.setItemText(2, _translate("Dialog", "В"))
        self.comboBox_class_letter.setItemText(3, _translate("Dialog", "Г"))
        self.button_add_student.setText(_translate("Dialog", "Добавить ученика"))
        self.button_show_student.setText(_translate("Dialog", "Показать учеников"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
