# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 208)
        self.input_password = QtWidgets.QLineEdit(Dialog)
        self.input_password.setGeometry(QtCore.QRect(80, 90, 151, 21))
        self.input_password.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.input_password.setText("")
        self.input_password.setMaxLength(32764)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.input_login = QtWidgets.QLineEdit(Dialog)
        self.input_login.setGeometry(QtCore.QRect(80, 60, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_login.setFont(font)
        self.input_login.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.input_login.setText("")
        self.input_login.setObjectName("input_login")
        self.title_name = QtWidgets.QLabel(Dialog)
        self.title_name.setGeometry(QtCore.QRect(55, 10, 170, 41))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title_name.setFont(font)
        self.title_name.setStyleSheet("")
        self.title_name.setObjectName("title_name")
        self.label_login = QtWidgets.QLabel(Dialog)
        self.label_login.setGeometry(QtCore.QRect(20, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName("label_login")
        self.name_password = QtWidgets.QLabel(Dialog)
        self.name_password.setGeometry(QtCore.QRect(20, 90, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_password.setFont(font)
        self.name_password.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.name_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_password.setObjectName("name_password")
        self.button_sign_in = QtWidgets.QPushButton(Dialog)
        self.button_sign_in.setGeometry(QtCore.QRect(90, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_sign_in.setFont(font)
        self.button_sign_in.setStyleSheet("font: 11pt \"Source Sans Pro\";")
        self.button_sign_in.setAutoRepeatDelay(300)
        self.button_sign_in.setAutoDefault(True)
        self.button_sign_in.setDefault(False)
        self.button_sign_in.setFlat(False)
        self.button_sign_in.setObjectName("button_sign_in")
        self.button_fogot_password = QtWidgets.QPushButton(Dialog)
        self.button_fogot_password.setGeometry(QtCore.QRect(150, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_fogot_password.setFont(font)
        self.button_fogot_password.setStyleSheet("QPushButton {\n"
"    font: 8pt \"Source Sans Pro\";\n"
"    color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 0, 255);\n"
"    text-decoration: underline;\n"
"}")
        self.button_fogot_password.setAutoRepeatDelay(300)
        self.button_fogot_password.setAutoDefault(False)
        self.button_fogot_password.setDefault(False)
        self.button_fogot_password.setFlat(True)
        self.button_fogot_password.setObjectName("button_fogot_password")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_name.setText(_translate("Dialog", "Авторизация"))
        self.label_login.setText(_translate("Dialog", "Логин"))
        self.name_password.setText(_translate("Dialog", "Пароль"))
        self.button_sign_in.setText(_translate("Dialog", "Войти"))
        self.button_fogot_password.setText(_translate("Dialog", "Забыли пароль?"))
